### ISSUE TITLE
Machine-wide install

### ISSUE THREAD

**Issue by xdvarpunen** [electron/windows-installer#127]
Hello,

How is machine-wide installation achieved with windows-installer module?

-XDVarpunen

**Comment by Unforgiven-wanda** [comment]
I believe it can't be done. This tool relies on Squirrel, and of its core principles is to have a painless, invisible install/uninstall. Meaning that your app will invariably be installed to the user appdata, and that to prevent any permission issues and other unpleasantness.

However, I believe electron-builder would allow you to do this, since you can package your installer using NSIS.

**Comment by xdvarpunen** [comment]
Use .msi: it does the machine-wide installation: 

| Config Name           | Required | Description |
| --------------------- | -------- | ----------- |
noMsi | 	No | Should Squirrel.Windows create an MSI installer?

https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/machine-wide-installs.md

WIX <3
