### ISSUE TITLE
Can't find icon when building via Github Actions

### ISSUE THREAD

**Issue by JaspervRijbroek** [electron/windows-installer#326]
Hello,

When I am building a windows installer on windows via Github Actions.
I receive a message that the file could not be found. I have checked the image permissions and containing folder permissions but these are correct (Everyone has full control).

The command that gives the error is the following (all directories and files created by the same user):
```
Tue, 28 Jan 2020 17:22:17 GMT electron-windows-installer:spawn Spawning C:\actions-runner\_work\frontender.desktop\frontender.desktop\node_modules\electron-winstaller\vendor\rcedit.exe C:\actions-runner\_work\frontender.desktop\frontender.desktop\electron-out\Frontender-win32-x64\Update.exe --set-icon C:\frontender-assets\main.ico
```

But when I run this command in PowerShell then the icon is being set without messages.

Do you have any idea what the issue could be?

Kind Regards and Thanks in Advance,

**Comment by malept** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
