### ISSUE TITLE
What are the differences between electron-installer-windows and windows-installer

### ISSUE THREAD

**Issue by mahnunchik** [electron/windows-installer#341]
What are the differences between [`electron-installer-windows`](https://github.com/electron-userland/electron-installer-windows) and [`windows-installer`](https://github.com/electron/windows-installer/)?

**Comment by malept** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by mahnunchik** [comment]
Done!

@malept could you answer it here: https://discuss.atom.io/t/what-are-the-differences-between-electron-installer-windows-and-windows-installer/76381
