### ISSUE TITLE
It doesn't work with Electron latest version.

### ISSUE THREAD

**Issue by burakkp** [electron/windows-installer#348]
Hi folks,

I updated my electron app to the latest version(9.0.5), After that, I faced the problem. All build steps good working on the terminal but I want to run app.exe from generated windows-installer It doesn't work. I returned back to prev version(8.3.4). Everything is good for working. I don't understand what is the problem. Is anybody can help me?

**Comment by malept** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
